In [85]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

# 1. Các phép toán vector và ma trận

(a) *Độ dài của vector*

In [86]:
def compute_vector_length(vector):
    len_of_vector = np.linalg.norm(vector)
    return len_of_vector

(b) *Phép tích vô hướng*

In [87]:
def compute_dot_product(vector1, vector2):
    result = np.dot(vector1, vector2)
    return result

(c) *Nhân vector với ma trận*

In [88]:
def matrix_multi_vector(matrix, vector):
    result = np.dot(matrix, vector)
    return result

(d) *Nhân ma trận với ma trận*

In [89]:
def matrix_multi_matrix(matrix1, matrix2):
    result = np.dot(matrix1, matrix2)
    return result

*(e) Ma trận nghịch đảo*

In [90]:
def inverse_matrix(matrix):
    result = np.linalg.inv(matrix)
    return result

# 2. Eigenvector và eigenvalues

In [91]:
def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues,eigenvectors

# 3. Cosine Similarity

In [92]:
def compute_cosine(v1, v2):
  cos_sim = compute_dot_product(v1,v2) / (compute_vector_length(v1)*compute_vector_length(v2))
  return cos_sim

# Bài tập

In [93]:
# Câu 1
vector = np.array([-2, 4, 9, 21])
result = compute_vector_length([vector])
print(round(result, 2))

23.28


In [94]:
# Câu 2
v1 = np. array([0, 1, -1, 2])
v2 = np. array([2, 5, 1, 0])
result = compute_dot_product(v1, v2)
print(round(result, 2))

4


In [95]:
# Câu 3
x = np. array([[1, 2],
               [3, 4]])
k = np. array([1, 2])
print('result \n', x.dot(k))

result 
 [ 5 11]


In [96]:
# Câu 4
x = np. array([[-1, 2],
               [3, -4]])
k = np. array([1, 2])
print('result \n', x@k)

result 
 [ 3 -5]


In [97]:
# Câu 5
m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
result = matrix_multi_vector(m, v)
print(result)

[3 1]


In [98]:
# Câu 6
m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3], [6, 1], [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)

[[  6  -1]
 [-16 -10]]


In [99]:
# Câu 7
m1 = np.eye(3)
m2 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
result = m1 @ m2
print(result)


[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [100]:
# Câu 8
m1 = np.eye(2)
m1 = np. reshape(m1, (-1, 4))[0]
m2 = np. array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print(result)

[5. 5. 5. 5.]


In [101]:
# Câu 9
m1 = np. array([[1, 2], [3, 4]])
m1 = np. reshape(m1, (-1, 4), "F")[0]
m2 = np. array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print(result)

[29 29 29 29]


In [102]:
# Câu 10
m1 = np. array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


In [103]:
# Câu 11
matrix = np. array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [104]:
# Câu 12
x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x,y)
print(round(result, 3))

0.577
